// <auto-generated />
using MYAZ303_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MYAZ303MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221109132009_Kayit")]
    partial class Kayit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MYAZ303_MVC.Models.Album", b =>
                {
                    b.Property<int>("albumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("albumID"));

                    b.Property<string>("albumAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sarkiID")
                        .HasColumnType("int");

                    b.HasKey("albumID");

                    b.ToTable("Albumler");
                });

            modelBuilder.Entity("MYAZ303_MVC.Models.Sanatci", b =>
                {
                    b.Property<int>("sanatciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sanatciID"));

                    b.Property<int>("albumID")
                        .HasColumnType("int");

                    b.Property<string>("sanatciAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sanatciID");

                    b.ToTable("Sanatcilar");
                });

            modelBuilder.Entity("MYAZ303_MVC.Models.Sarki", b =>
                {
                    b.Property<int>("sarkiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sarkiID"));

                    b.Property<string>("sarkiAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("sure")
                        .HasColumnType("real");

                    b.HasKey("sarkiID");

                    b.ToTable("Sarkilar");
                });
#pragma warning restore 612, 618
        }
    }
}
