// <auto-generated />
using MYAZ303_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MYAZ303MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221109165648_Kayit2")]
    partial class Kayit2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MYAZ303_MVC.Models.Sarki", b =>
                {
                    b.Property<int>("sarkiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sarkiID"));

                    b.Property<string>("album")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sanatci")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sarkiAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("sure")
                        .HasColumnType("real");

                    b.HasKey("sarkiID");

                    b.ToTable("Sarkilar");
                });
#pragma warning restore 612, 618
        }
    }
}
